### ISSUE TITLE
Why not mysql-connector-python?

### ISSUE THREAD

**Issue by netpie** [aio-libs/aiomysql#10]
aiomysql depends and reuses most parts of PyMySQL . What about  derived from mysql-connector-python?

**Comment by methane** [comment]
mysql-connector-python will use libmysqlclient to boost performance.  It may or may not support asynchronous io. MariaDB's libmysqclient support it from recently, but Oracle's not support it.

I'll add speedup module written in C or Cython only for packet parsing to ease aiomysql use it.

**Comment by jettify** [comment]
From other hand mysql-connector-python is not available from PyPI [1] and only way to reuse parts is by copying whole driver. 

[1] https://wiki.openstack.org/wiki/PyMySQL_evaluation

**Comment by netpie** [comment]
thanks! prefer to aiopymysql now :)
