### ISSUE TITLE
Connecting via URL instead of separate connection values

### ISSUE THREAD

**Issue by sebastian-malek** [aio-libs/aiomysql#102]
Could we connect by passing the connection details via an URL instead of having separate host, port, etc. variables? [Similar to what aioamqp has with its from_url function](https://github.com/Polyconseil/aioamqp/blob/b1d11024c658e03722bee57f97a9ced8e3e6b1bc/aioamqp/__init__.py#L76).

**Comment by jettify** [comment]
@sebastian-malek it is very easy to create your own helper function, 
```python
async def connect_from_uri(uri):
    p = urlsplit(uri)
    connection = await aiomysql.connect(host=p.hostname, port=p.port)
    return connection
```
`PyMySQL` do not support URIs so I think `aiomysql` should not too.

**Comment by sebastian-malek** [comment]
@jettify thanks!

closing this issue

**Comment by r0m4n-z** [comment]
@jettify Just discovered this issue: would you review PR with such feature in `aiomysql` or you still think this is not what this library should contain? It seems to be pretty convenient in some cases and would save time for those who wants to use it.
