### ISSUE TITLE
'Connection' object has no attribute 'password'

### ISSUE THREAD

**Issue by BurnellLiu** [aio-libs/aiomysql#105]
aiomysql version: 0.0.8
os version: win10

When i use this functinon:
`__pool = await aiomysql.create_pool(
        host=kw.get('host', 'localhost'),
        port=kw.get('port', 3306),
        user=kw['user'],
        password=kw['password'],
        db=kw['db'],
        charset=kw.get('charset', 'utf8'),
        autocommit=kw.get('autocommit', True),
        maxsize=kw.get('maxsize', 10),
        minsize=kw.get('minsize', 1),
        loop=loop
    )`

I found a error:
 File "C:\Program Files (x86)\Python35-32\lib\site-packages\aiomysql\connection.py", line 699, in _request_authentication
    **data = _scramble_323(self.password.encode('latin1'),
AttributeError: 'Connection' object has no attribute 'password'**

I think it shoud be:
**data = _scramble_323(self._password.encode('latin1'),**

Thanks

**Comment by jettify** [comment]
Good catch! Wold you like to submit PR?

**Comment by BurnellLiu** [comment]
I am sorry

**Comment by jettify** [comment]
fixed in https://github.com/aio-libs/aiomysql/commit/eae25fd1aecab8620aa35c7cd2bedd7e96eac6a5
