### ISSUE TITLE
Non-recurrent exception: AssertionError: yield from wasn't used with future

### ISSUE THREAD

**Issue by SilverIceStas** [aio-libs/aiomysql#109]
Sometimes I catch an unexpected and not very obvious exception:

Traceback (most recent call last):

> 
>   File "/home/si/xxxxxx/middleware/db.py", line 41, in execute
>     tr = yield from conn.begin()
>   File "/venv/lib/python3.5/site-packages/aiomysql/utils.py", line 61, in __iter__
>     resp = yield from self._coro
>   File "/venv/lib/python3.5/site-packages/aiomysql/sa/connection.py", line 166, in _begin
>     yield from self._begin_impl()
>   File "/venv/lib/python3.5/site-packages/aiomysql/sa/connection.py", line 175, in _begin_impl
>     yield from cur.execute('BEGIN')
>   File "/venv/lib/python3.5/site-packages/aiomysql/cursors.py", line 239, in execute
>     yield from self._query(query)
>   File "/venv/lib/python3.5/site-packages/aiomysql/cursors.py", line 460, in _query
>     yield from conn.query(q)
>   File "/venv/lib/python3.5/site-packages/aiomysql/connection.py", line 398, in query
>     yield from self._read_query_result(unbuffered=unbuffered)
>   File "/venv/lib/python3.5/site-packages/aiomysql/connection.py", line 582, in _read_query_result
>     yield from result.read()
>   File "/venv/lib/python3.5/site-packages/aiomysql/connection.py", line 835, in read
>     first_packet = yield from self.connection._read_packet()
>   File "/venv/lib/python3.5/site-packages/aiomysql/connection.py", line 520, in _read_packet
>     packet_header = yield from self._read_bytes(4)
>   File "/venv/lib/python3.5/site-packages/aiomysql/connection.py", line 558, in _read_bytes
>     data = yield from self._reader.readexactly(num_bytes)
>   File "/usr/local/lib/python3.5/asyncio/streams.py", line 670, in readexactly
>     block = yield from self.read(n)
>   File "/usr/local/lib/python3.5/asyncio/streams.py", line 627, in read
>     yield from self._wait_for_data('read')
>   File "/usr/local/lib/python3.5/asyncio/streams.py", line 457, in _wait_for_data
>     yield from self._waiter
>   File "/usr/local/lib/python3.5/asyncio/futures.py", line 362, in __iter__
>     assert self.done(), "yield from wasn't used with future"
> AssertionError: yield from wasn't used with futur

"execute" is standard function, witch used in the project and, in most cases, used successfully:

```
37:    def execute(self, query):
38:        res = None
39:        try:
40:            with (yield from self._engine) as conn:
41:                tr = yield from conn.begin()
42:                try:
43:                    res = yield from conn.execute(query)
44:                    yield from tr.commit()
45:                except (SQLAlchemyError, MySQLError):
46:                    yield from tr.rollback()
47:                finally:
48:                    yield from tr.close()
49:        except (SQLAlchemyError, MySQLError) as e:
50:            print(e)
51:        return res
```

Mysql global_log for this moment:

> 160919  9:29:06	   36 Connect	test@localhost on test
> 		   36 Query	SET AUTOCOMMIT = 0
> 		   36 Query	BEGIN
> 		   37 Query	SELECT company_category_user.user FROM company_category_user WHERE *****
> 		   36 Query	COMMIT
> 		   36 Query	BEGIN
> 		   37 Query	SELECT DISTINCT vehicle_car.id FROM vehicle_car_cache_category INNER JOIN vehicle_car on ***** WHERE *****
> 		   36 Query	COMMIT
> 		   36 Query	BEGIN
> 		   37 Query	SELECT DISTINCT vehicle_car.id FROM vehicle_car WHERE *****
> 		   36 Query	COMMIT
> 		   36 Query	BEGIN
> 160919  9:29:43	   37 Connect	test@localhost on test
> 		   37 Query	SET AUTOCOMMIT = 0
> 		   37 Query	BEGIN

The first three requests are made using the same "execute" function.
mysql-error log have no record.

An additional, that we crash in conn.begin() the code has time to activate transaction (catch the exception-in-exception - aiomysql.sa.exc.InvalidRequestError: Cannot release a connection with not finished transaction)

Tech summary:
System 1:
   Python 3.5.2 
   aiomysql==0.0.9
   PyMySQL==0.7.9
   mysqld  Ver 5.5.50-0ubuntu0.14.04.1-log for debian-linux-gnu on x86_64 ((Ubuntu))
   Linux vagrant-ubuntu-trusty-64 3.13.0-87-generic #133-Ubuntu SMP Tue May 24 18:32:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

System 2:
   Python 3.5.1
   aiomysql==0.0.7
   PyMySQL==0.6.7
   mysqld  Ver 5.5.49-0ubuntu0.14.04.1 for debian-linux-gnu on x86_64 ((Ubuntu))
   Linux ubuntu-1gb-nyc3-01 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

What additional information I can provide to you for help?

**Comment by jettify** [comment]
@SilverIceStas have you solved this issue?

**Comment by SilverIceStas** [comment]
@jettify 
a) rebuild query; 
b) separate two logical ways: select and execute. Select is an execute with fetch (to array, I do not want return cursor, because it can be a potential pool-leak). And finally transaction commit.
c) update mysql to 5.6.

I think in some conditions, the mysql return corrupted data and somewhere in the yield-chain was broken.

**Comment by jettify** [comment]
thanks for update!
