### ISSUE TITLE
rename Connection.wait_closed()

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiomysql#11]
`asyncio.AbstractServer` uses the following idiom:
- `close()` closes connection asynchronously, it's regular function.
- `wait_closed()` is a coroutine that waits for actual closing.

`Connection.wait_closed()` has different behavior: it sends disconnection signal to server and after that closes connection.

I guess  rename it to `.ensure_closed()`.

**Comment by jettify** [comment]
+1. I missed idea behind `wait_closed()`
