### ISSUE TITLE
use sqlalchemy save failed

### ISSUE THREAD

**Issue by larry-dev** [aio-libs/aiomysql#117]
![image](https://cloud.githubusercontent.com/assets/18585750/19339571/c577c28a-9156-11e6-802c-f3be158636af.png)

but mysql>user table isn't data

![image](https://cloud.githubusercontent.com/assets/18585750/19339596/e1b87a70-9156-11e6-8424-d13c6d6bc066.png)

**Comment by LarryLiuPT** [comment]
python version 3.5.2
aiomysql version 0.0.9
sqlalchemy version 1.1.1

**Comment by asvetlov** [comment]
Perhaps you've forget committing changes.
Or use `autocommit=True` option.

**Comment by jettify** [comment]
feel free to reopen with more information
