### ISSUE TITLE
Connections from Pool Keeps Getting Old Data from Database

### ISSUE THREAD

**Issue by j-beatzz** [aio-libs/aiomysql#121]
I have an API that executes code similar to this:
```
mysql = await create_pool(host='HOST', port=PORT, user='USER', password='PWORD', db='DB', loop=asyncio.get_event_loop())
async with mysql.acquire() as conn:
        async with conn.cursor() as cur:
            query_string = "SELECT * FROM table;"
            await cur.execute(query_string)
            rows = await cur.fetchall()
```

This works well to get the required data from the db the first time. However, on making the same request, over and over again even after changing the data in the database, I noticed that the results obtained from the piece of code is different from what is in the DB. What was returned was actually the result from before making changes to the db outside of the API.

Python version = 3.5.1
MySQL version = 5.6
Environment = Fedora 24

One thing I noticed is that when I explicitly called `conn.close()` after executing the query, it worked correctly. 

I am assuming this shouldn't be how to use `conn.close()` in this case?

**Comment by jettify** [comment]
Could you try to enable autocomit or change isolation level? probably you see dirty reads (https://en.wikipedia.org/wiki/Isolation_(database_systems)#Isolation_Levels.2C_Read_Phenomena_and_Locks)

**Comment by j-beatzz** [comment]
Interesting. Setting autocommit to True works. Thanks for the help.

**Comment by xiandong79** [comment]
I face the same issue today, I also have to set  autocommit to True.

not sure why a SELECT action needs to set  autocommit to True.
