### ISSUE TITLE
AttributeError: 'MySQLCompiler_mysqldb' object has no attribute 'result_map'

### ISSUE THREAD

**Issue by eg0r** [aio-libs/aiomysql#14]
Скачанном из PyPI версии 0.0.3 вылезает ошибка:

```
AttributeError: 'MySQLCompiler_mysqldb' object has no attribute 'result_map'
```

Вижу, что уже [исправлено](https://github.com/aio-libs/aiomysql/commit/fafe40abae0bd7bfc6d515eb4993fca02af9e30d), но в PyPI тоже нужно обновить.

**Comment by jettify** [comment]
Привет.
Выложил новую верснию на pypi:  https://pypi.python.org/pypi/aiomysql/0.0.4

**Comment by eg0r** [comment]
Спасибо :)
