### ISSUE TITLE
Any way to specify transaction isolation?

### ISSUE THREAD

**Issue by carn1x** [aio-libs/aiomysql#144]
I'd like to connect with a non-standard isolation level `READ UNCOMMITTED` (https://dev.mysql.com/doc/refman/5.7/en/innodb-transaction-isolation-levels.html). Is it possible to specify this in the connection parameters?

**Comment by carn1x** [comment]
Always assumed this was a connection parameter only (not reading the link I posted properly), and found it fine to set as the first query with `SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;`. It would be nice to understand if this sort of thing can be set in the connection parameters though, is there any scope for custom connection string?

**Comment by jettify** [comment]
Bit do not follow, what do you mean by scope of connection string?  scope of `SET TRANSACTION ...` ?  This depends on SQL query see more info here: https://dev.mysql.com/doc/refman/5.7/en/set-transaction.html  see section `Scope of Transaction Characteristics`, aiomysql do not add any magic

**Comment by jettify** [comment]
Closing for now, feed free to reopen with more information

**Comment by dalianzhu** [comment]
@jettify It seems no params in aiomysql.connection() to set the isolation level. Is there a way like 
```
aiomysql.connect(host='127.0.0.1', isolation_level='READ UNCOMMITTED' ....)
```
or can we set the level in each transaction session like:
```
async with conn.cursor() as cursor:
        ......
        await cursor.execute("SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED")
        ......
        await conn.commit()
```

**Comment by MartianLee** [comment]
I found that aiomysql.connect doesn't get the parameter 'isolation_level' now. But second solution works well. Thanks !
