### ISSUE TITLE
Very slow selection

### ISSUE THREAD

**Issue by unreg** [aio-libs/aiomysql#150]
Hi!

I have simple select ~2.5KK rows ```SELECT column_1, column_2 FROM table WHERE
        created > '2016-01-05 23:59:59' AND created < '2016-02-07 00:00:00';```

Benchmarks:
- mysql - 2 sec
- mysqlclient (fork MySQLdb) - 3.5 sec
- aiomysql - 40 sec.

How to aiomysql speed up? Possible change mysql-connector to mysqlclient?

**Comment by jettify** [comment]
Hi, could you please show code how you execute queries? do you use connection pool? Could you also check with PyMySQL? mysqlclient use C parser, aiomysql uses python parser from PyMySQL.

You can use sync library with asyncio, just wrap your queries with ThreadPoolExecutor. Also you may want to checkout https://github.com/aio-libs/aioodbc , and try access to MySQL with ODBC driver.

**Comment by unreg** [comment]
I use code from example, with pool and without, does not affect to result.

I checked only PyMySQL, it slightly differs - 36 sec. )) Therefore, and I asked if he could choose another connector.

**Comment by ihjmh** [comment]
can you check the package /aio/mysql/sa/engine

# try:
#     from sqlalchemy.dialects.mysql.pymysql import MySQLDialect_pymysql
# except ImportError:  # pragma: no cover
#     raise ImportError('aiomysql.sa requires sqlalchemy')
try:
    from sqlalchemy.dialects.mysql.mysqldb import MySQLDialect_mysqldb
except ImportError:  # pragma: no cover
    raise ImportError('aiomysql.sa requires sqlalchemy')

# _dialect = MySQLDialect_pymysql(paramstyle='pyformat')
# _dialect.default_paramstyle = 'pyformat'
_dialect = MySQLDialect_mysqldb()
# _dialect.default_paramstyle = 'pyformat'


change the code as above,it will let you use the mysqldb

btw,i haven't test if mysqldb can replace the pysqldb very well ,if you find any bugs ,please let me know :),
send to :      damonhowe2010@gmail.com

**Comment by jettify** [comment]
this is due to slow python parser, mariadb has async aware C driver, and it is possible to use it with asyncio, but thats require some time to implement...

**Comment by gaborbernat** [comment]
@jettify has this been solved?
