### ISSUE TITLE
aiomysql enabled cache?

### ISSUE THREAD

**Issue by wencan** [aio-libs/aiomysql#158]
aiomysql enabled cache?

OS: debian 8.7
python: 3.5.3/3.6.0
aiohttp: 1.3.3
aiomysql: 0.0.9

code:

    async def query(engine, _id):
        async with engine.acquire() as conn:
            async for row in conn.execute('SELECT title FROM tablename WHERE _id = "%s"' % _id):
                print(row)

    async def go(loop=None):
        async with create_engine(user='***', db='***', host='***', password='***', echo=True, loop=loop) as engine:
            await query(engine, 'id')

            await asyncio.sleep(10)
            await query(engine, 'id')

    loop = asyncio.get_event_loop()
    loop.run_until_complete(go())

I modified the data in sleep
However, the old value is still returned until the program restarts

**Comment by jettify** [comment]
Hi!
Can you try to enable `autocommit` mode? by default read/writes should be committed.

**Comment by wencan** [comment]
@jettify Thank you. The problem has been solved after autocommit is enabled.
