### ISSUE TITLE
Installs `tests` as a package on install from pip

### ISSUE THREAD

**Issue by danpozmanter** [aio-libs/aiomysql#181]
After installing, `tests` will be installed as a package in site-packages.

**Comment by jettify** [comment]
Interesting, we do not add tests explicitly in MANIFEST https://github.com/aio-libs/aiomysql/blob/master/MANIFEST.in

**Comment by Nothing4You** [comment]
I can't reproduce this.
Please raise a new issue if this is still an issue.
