### ISSUE TITLE
Does aioMysql.sa support MetaData.create_all?

### ISSUE THREAD

**Issue by JesseRo** [aio-libs/aiomysql#184]
i create a engine using 'aiomysql.sa.create_engine' and  then i'm trying to create tables using SQLAlchemy's api 'MetaData.create_all':
```
    engine = await aiomysql.sa.create_engine(
        db=conf['database'],
        host=conf['host'],
        port=conf['port'],
        user=conf['user'],
        password=conf['password'],
        minsize=conf['minsize'],
        maxsize=conf['maxsize']
    )
    meta.create_all(engine)
```
but raise errors:
>   File "D:\work\code-git\aio-market\app\db.py", line 19, in init_mysql
>     meta.create_all(engine)
>   File "C:\Users\Administrator\Anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 3857, in create_all
>     bind._run_visitor(ddl.SchemaGenerator,
> AttributeError: 'Engine' object has no attribute '_run_visitor'

but then i retry without aiomysql:
```
engine = sqlalchemy.create_engine('mysql+pymysql://user:pwd@localhost:3306/aio-market')
meta.create_all(engine)
```
and it works..

am i doing anything wrong, or aioMysql.sa do not support MetaData.create_all for now?

**Comment by jettify** [comment]
Sorry MetaData.create_all is not supported, you may use something like:
https://github.com/aio-libs/aiohttp_admin/blob/master/demos/blog/aiohttpdemo_blog/generate_data.py#L37-L43

**Comment by JesseRo** [comment]
@jettify Ok..Thank you..
