### ISSUE TITLE
SQLAlchemy Dialects

### ISSUE THREAD

**Issue by jairhenrique** [aio-libs/aiomysql#189]
It would be nice if SQLAlchemy support was done using the [dialects](http://docs.sqlalchemy.org/en/latest/dialects/index.html).

```python
from sqlalchemy import create_engine
engine = create_engine('mysql+aiomysql://...')
....
```

**Comment by jettify** [comment]
Not sure it is possible, since `sqlalchemy` is not async library and aiomysql/aiopg uses `sqlalchemy` most of the time as query compiler.
