### ISSUE TITLE
python version for the __del__ method

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiomysql#19]
@asvetlov, for now we use `` __del__`` method with python `` sys.version_info >= (3, 4)`` but ``aiohttp.TCPConnector`` uses ``sys.version_info >= (3, 4, 1)``. I am little bit confused should aiomysql have restriction ``>= (3, 4, 1)`` too?

**Comment by asvetlov** [comment]
Should be `(3, 4, 1)` everywhere.
Python 3.4.0 has a bug which sometimes leads to core dump when `__del__` is used.

**Comment by jettify** [comment]
Fixed via https://github.com/aio-libs/aiomysql/commit/5448eeb9cc6166511fb4a16f5e02c1e4b2bb0172
Thanks!
