### ISSUE TITLE
Sqlalchemy metadata.create_all does not work

### ISSUE THREAD

**Issue by Reonaydo** [aio-libs/aiomysql#199]
In continue to #108

Creating tables via metadata.create_all is not possible

` AttributeError: 'Engine' object has no attribute '_run_visitor'`

**Comment by jettify** [comment]
SQLA used as query builder most of the times, so not all APIs supported only essential ones. SQLA is inherently sync so it is not easy or sometimes even possible to support all functionality.

**Comment by bsergean** [comment]
Would it be hard to support this ?

Other examples have create database examples, but not the sqlalchemy ones.
