### ISSUE TITLE
Autocommit on connection pool

### ISSUE THREAD

**Issue by magnamatt** [aio-libs/aiomysql#200]
Hi,

Firstly, thanks for an awesome piece of software.

The only real issue I have had is connection pooling with autocommit set to false (the default for aiomysql and pymysql) returns stale and inconsistent results with SELECT operations. The autocommit option is not in the aiomysql pool docs and this is a little misleading. Perhaps this default behaviour should be changed or the option added to the pool docs section of aiomysql.

**Comment by jettify** [comment]
I do not think we can change default behavior, idea to be consistent with PyMySQL, as for the docs, you absolutely right, they could be better. Would you like to update docs?

**Comment by magnamatt** [comment]
Apologies for the delay in reply. I would be happy to help.

**Comment by jettify** [comment]
@magnamatt no problem at all :)

**Comment by alk3mist** [comment]
Hello, I noticed the strange behaviour of Connection.commit(). It didn't actually do a commit. And when the same connection is acquired from a pool, a select shows updated data, but with other connection, the data remains unchanged. That problem doesn't appear when I use await connection.execute('commit').

**Comment by Tehtehteh** [comment]
@jettify I encountered same problem with `autocommit` set to `False` by default.
And as far as I see docs haven't been updated to state this.
Do you still need help with this?

**Comment by jettify** [comment]
@Tehtehteh yes, any help very appreciated!

**Comment by jettify** [comment]
closing this issue feel free to create new one
