### ISSUE TITLE
Issue with escaping in DROP and CREATE TABLE statements 

### ISSUE THREAD

**Issue by Tehtehteh** [aio-libs/aiomysql#215]
If we use statements DROP/CREATE with escaping, i.e.
```
async def query(query, args):
    async with pool.get() as conn:
        async with conn.cursor(aiomysql.DictCursor) as cur:
            await cur.execute(query, args)
```
And we call
```
async def test():
    query = "CREATE TABLE %s(id int)"
    await query(query, args=['test'])
    query = "DROP TABLE IF EXISTS %s"
    await query(query, args=['test'])
```
Escaped query would look like `'CREATE TABLE \\'test\\'(id int)'`
And it produces MySQL Error:
```
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''test'(id int)' at line 1")
```
Am I doing something wrong?

**Comment by jettify** [comment]
I stumbled on this few times too, as far as I can tell that mysql clients do not support parameter substitution for metadata as result pymysql/aiomysql follow the suite.
https://stackoverflow.com/questions/6618344/python-mysqldb-and-escaping-table-names

**Comment by Tehtehteh** [comment]
Ok. So this isn't an issue I guess and we should not pass arguments to this kind of statements. Understood, thanks :)
