### ISSUE TITLE
LOAD LOCAL INFILE statement not work 

### ISSUE THREAD

**Issue by bitaps** [aio-libs/aiomysql#22]
Mysql statment "LOAD LOCAL INFILE ... "  not working 

 changelog PyMySQLt ## 0.6.4
* Support "LOAD LOCAL INFILE". 

I try to use this LOAD LOCAL INFILE, using param client_flag: LOCAL_FILES  I turn on support local files for connection. But aiomysql return Exception on LOAD LOCAL INFILE statement. Please check and add this feature.

Thank you

**Comment by jettify** [comment]
```LOAD LOCAL INFILE``` is not implemented. This feature was added to PyMySQL in PR: https://github.com/PyMySQL/PyMySQL/pull/279 as far as I can see should not be hard to port. I will try to add it soon.

**Comment by jettify** [comment]
Implemented via https://github.com/aio-libs/aiomysql/pull/23
