### ISSUE TITLE
Unable to set a connect_timeout

### ISSUE THREAD

**Issue by terrisgit** [aio-libs/aiomysql#257]
aiomysql==0.0.12

Reading through the code, kwargs passed to create_pool() are captured and passed along. The code looks correct but setting connect_timeout to 1 versus 1000 makes no difference. The timeout is always two minutes and a few seconds. Something like:

```
pool = await aiomysql.create_pool(user=user, db=database, host=host,
      password=password, port=port, connect_timeout=1 )

**Comment by jettify** [comment]
That is a good catch, we need to wrap `open_connection` into `asyncio.wait_for` and add pass `connect_timeout` there
https://github.com/aio-libs/aiomysql/blob/d77a97d8d1690249f25312d1ea12c64a3c165b37/aiomysql/connection.py#L456-L466

**Comment by jettify** [comment]
would you like to create PR?

**Comment by mpavelka** [comment]
+1, is there a progress?

**Comment by terrycain** [comment]
Once we've fixed SSL (hopefully in the next few days) I'll PR this, should be simple.

**Comment by VeridianDynamics** [comment]
Has this been solved and the issue is just forgotten, or has there been some unforeseen roadblock? Thanks.

**Comment by M4v3R** [comment]
@terrycain did you get to implement this PR in the end? Thanks.

**Comment by terrycain** [comment]
I didn't, I completely forgot :smile:, I'll have a crack at this on the weekend unless someone else wishes to do so.
