### ISSUE TITLE
DictCursor cursorclass breaks sqlalchemy engine fetching

### ISSUE THREAD

**Issue by iScrE4m** [aio-libs/aiomysql#263]
Python 3.5, running on Linux, aiomysql 0.0.12

It can definitely be criticized, that I even tried to pass DictCursor into create_engine as a cursorclass, but I believe that the library should either ignore the cursor choice, or not accept the kwarg at all and thrown an exception, since it relies on the classic one. If it can work other cursor classes, It should at least check if they are compatible (or blacklist uncompatible ones)?

```
...
    /usr/local/lib/python3.5/dist-packages/aiomysql/sa/result.py", line 88, in as_tuple
    return tuple(self[k] for k in self)
  File "/usr/local/lib/python3.5/dist-packages/aiomysql/sa/result.py", line 88, in <genexpr>
    return tuple(self[k] for k in self)
  File "/usr/local/lib/python3.5/dist-packages/aiomysql/sa/result.py", line 63, in __getitem__
    return self._row[index]
    KeyError: 0
```

**Comment by jettify** [comment]
aiomysql supports dict cursors but not for SA layer, you are right we need to throw exception in case cursor class specified in create_engine. Would you like to create PR with a fix?
