### ISSUE TITLE
Remove a connection from aiomysql.Pool

### ISSUE THREAD

**Issue by terrisgit** [aio-libs/aiomysql#286]
Is there a way to remove a bad connection from a connection pool when using context managers?

When my app encounters a MySQL error, it closes the connection pool and creates a new one because aiomysql doesn't automatically remove bad connections from the pool. This is not a nice thing to do if other connections managed by the pool are running queries.

As an enhancement, I need to zero down permanent connection-related errors versus recoverable errors such as "deadlock victim." I haven't had enough time to experiment.

Searching for either doesn't provide answers but maybe I'm not looking closely enough:
- pymysql remove connection pool
- aiomysql remove connection pool

**Comment by jettify** [comment]
Can you define bad connection?  If you close connection and return it to the pool, pool will drop it and create new one instead. If you return connection to the pool with unfinished transaction, connection will be dropped too. 

So if you have bad connection, just close it and release it to the pool.

**Comment by jettify** [comment]
see logic here:
https://github.com/aio-libs/aiomysql/blob/e95df7407bd1ab4612c6307019ea08ab6171d1e8/aiomysql/pool.py#L198-L222

**Comment by terrisgit** [comment]
I need to determine which exceptions warrant removing a connection from a pool. eg for deadlock victim, no, for connection error, yes. Not sure this clear cut.

**Comment by terrisgit** [comment]
You can close this -- I'll just try closing the connection when I get an exception.
