### ISSUE TITLE
Support Python 3.5 features

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiomysql#29]
Python 3.5 expecte to be released soon  [1]. For now aiomysql passes tests against Python 3.5, but it would be nice if we merge ``async/await`` features from  https://github.com/aio-libs/aiomysql/compare/master...await

Any thoughts on this?

[1] https://www.python.org/dev/peps/pep-0478/

**Comment by asvetlov** [comment]
Sounds good but we should find a way for running test suite even by python without async/await support.

**Comment by asvetlov** [comment]
Fixed by #29
