### ISSUE TITLE
SAConnection example error

### ISSUE THREAD

**Issue by IdeoG** [aio-libs/aiomysql#307]
Please fix 
``` python
await conn.commit()
```
SAConnection doesn't have commit method. It should be changed to, for example, 

``` python
await conn.execute("commit")
```

https://github.com/aio-libs/aiomysql/blob/master/examples/example_simple_sa.py#L33

Best regards,
Alex.

**Comment by jettify** [comment]
good catch, would you like to submit PR with simple fix?

**Comment by IdeoG** [comment]
Done @jettify
