### ISSUE TITLE
import errror

### ISSUE THREAD

**Issue by ko-han** [aio-libs/aiomysql#311]
![image](https://user-images.githubusercontent.com/21136164/42357830-5e536648-810c-11e8-80de-1976a567b346.png)
![image](https://user-images.githubusercontent.com/21136164/42357935-da0de240-810c-11e8-83f5-a50dbe214ab2.png)
I got import errror when run aiomysql, but it seems I already have pymysql installed.

**Comment by and800** [comment]
duplicated #302
quick fix: install `pymysql<0.9`

**Comment by ko-han** [comment]
Sorry, didn't see it. Thank you very much.

**Comment by jettify** [comment]
Closing for now as dup
