### ISSUE TITLE
PyPi releases do not always match repo code

### ISSUE THREAD

**Issue by mal** [aio-libs/aiomysql#322]
While trying to work out why installing `0.0.17` still triggered the issue outlined in #302, I started looking at other versions and discovered that a few of them don't appear to match the code tagged for that release in this repo.

I've done a rudimentary check on the last 5 versions by doing a very lazy test, just checking if the version of `pymysql` matches between the git tag and the pypi release, here are the results:

[`0.0.15`](https://github.com/aio-libs/aiomysql/blob/v0.0.15/setup.py#L7): match
```sh
$ docker container run -it --rm python pip install aiomysql==0.0.15 | grep -F 'Collecting PyMySQL'                                                                                                                 
Collecting PyMySQL>=0.7.5 (from aiomysql==0.0.15)
```

[`0.0.16`](https://github.com/aio-libs/aiomysql/blob/v0.0.16/setup.py#L7): doesn't match
```sh
$ docker container run -it --rm python pip install aiomysql==0.0.16 | grep -F 'Collecting PyMySQL'
Collecting PyMySQL<0.9,>=0.7.5 (from aiomysql==0.0.16)
```
[`0.0.17`](https://github.com/aio-libs/aiomysql/blob/v0.0.17/setup.py#L7): doesn't match
```sh
$ docker container run -it --rm python pip install aiomysql==0.0.17 | grep -F 'Collecting PyMySQL'
Collecting PyMySQL<=0.9.2,>=0.9 (from aiomysql==0.0.17)
```

[`0.0.18`](https://github.com/aio-libs/aiomysql/blob/v0.0.18/setup.py#L7): no release
```sh
$ docker container run -it --rm python pip install aiomysql==0.0.18 | grep -F 'Collecting PyMySQL'
err: No matching distribution found for aiomysql==0.0.18
```

[`0.0.19`](https://github.com/aio-libs/aiomysql/blob/v0.0.19/setup.py#L7): match
```sh
$ docker container run -it --rm python pip install aiomysql==0.0.19 | grep -F 'Collecting PyMySQL'
Collecting PyMySQL<=0.9.2,>=0.9 (from aiomysql==0.0.19)
```

At best this is awfully confusing because according to the code `0.0.17` was the first release to have the conservative version pinning for `pymysql`, but in fact that's some how made it into the `0.0.16` release (which the code doesn't reflect) but _not_ into `0.0.17`.

It's a little unsettling to find that the versions released in PyPi don't always match the tagged code releases. Is this some sort of mistake or quirk in the shipping process? 😕 

Possibly related: https://github.com/aio-libs/aiomysql/issues/318

**Comment by terrycain** [comment]
0.0.17 was my bad, I attempted to build 0.0.18 but forgot to versionbump.

**Comment by terrycain** [comment]
@jettify is it worth getting travis to somehow republish 0.0.17?

**Comment by webknjaz** [comment]
@terrycain you cannot edit published dists.

**Comment by jettify** [comment]
At first, I did deploy manually so something could be missing, but now we have build script so, I believe the situation will improve, also @terrycain watching my back now.

**Comment by jettify** [comment]
We still need to manually bump version and updated changes, if someone has ideas how to improve this please share.

**Comment by webknjaz** [comment]
@jettify I have a completely tested and working flow where the only thing needed is just pushing a new tag. It's a single source of truth.

**Comment by terrycain** [comment]
> We still need to manually bump version

I've solved that in the past with `bumpversion` which has always worked for me :D

**Comment by webknjaz** [comment]
Which proves to be error-prone because of human presence in deployment chain.

**Comment by webknjaz** [comment]
@jettify @terrycain do you still want hardcoded version based flow?

**Comment by terrycain** [comment]
@webknjaz im not too fussed, if we can push a tag and thats all, as you said less error prone is better.

You got an example of that magical solution, im interested.

**Comment by terrycain** [comment]
Sure, as long as @jettify has no objections

**Comment by webknjaz** [comment]
@jettify?

**Comment by webknjaz** [comment]
It looks like @jettify doesn't care...

**Comment by terrycain** [comment]
Sure raise pr :).

I converted one of my projects to setuptools SCM the other day. Really nice

**Comment by jettify** [comment]
I am on long business trip, do not have lots of time right now. Will take a look once back to the town.

**Comment by webknjaz** [comment]
@jettify still there?

**Comment by webknjaz** [comment]
@jettify?

**Comment by jettify** [comment]
So `setuptools-scm` capable to fetch git tag and bump version in __init__ file?

**Comment by webknjaz** [comment]
with setuptools-scm you don't need to store version in a python file (but there's an option to do so). you can grab the installed version via pkg_resources.

**Comment by jettify** [comment]
I think having version in `__init__` file is important other then that, how that version is bumped I do not mind.

**Comment by webknjaz** [comment]
so when current commit is tagged, setuptools sets version to that tag value, if it's not tagged then version will be tag+patch_bump+local_version_spec.
so for `v1.0.0` it'd be `1.0.0`, but for the next commit it'd be `1.0.1dev0+ghash.date`

**Comment by webknjaz** [comment]
So I'll do smth like https://github.com/pytest-dev/pytest/blob/master/setup.py#L29 then

**Comment by jettify** [comment]
But version is not present in git ...

**Comment by webknjaz** [comment]
And yet it's in sync with the source

**Comment by jettify** [comment]
Is it possible to have commit that bumps version?

**Comment by webknjaz** [comment]
Why would you need it? It creates desynchronized source

**Comment by webknjaz** [comment]
You need a version in dist because it doesn't have Git tree context. Git itself has tags. It'd be pointless to have a file different from a tag.

**Comment by asvetlov** [comment]
@webknjaz does git plugin replace `__version__` in top-level `__init__.py` with an actual release number when `sdist` tarball is uploaded to pypi?

**Comment by webknjaz** [comment]
Almost: it generates a new module. So I'd not combine it with other code and have a separate file for version.

**Comment by webknjaz** [comment]
e.g. `__version__.py` or so

**Comment by webknjaz** [comment]
@jettify @asvetlov so?

**Comment by asvetlov** [comment]
In my experience release publishing requires a little more work than just version pinning.
At least changelog should be updated.
It needs extra manual steps. Changing a version string in `__init__.py` is not a big deal taking into account all other actions.
It just not my point of pain honestly.

**Comment by webknjaz** [comment]
You should always keep in mind to match the tag version with source anyway. I think that if you maintain a ton of dists this simple thing makes release process much easier.
As for changelog, I think this should be automated as well. I'm already working on a bot which enforces change fragments presence in PRs, at some point I hope to have an App or an Action improving the release as well.

**Comment by webknjaz** [comment]
@jettify ?
