### ISSUE TITLE
Add _binary prefix for binary data

### ISSUE THREAD

**Issue by LemonPi** [aio-libs/aiomysql#323]
This was a problem introduced in MySQL 5.6.27 and pointed out https://github.com/PyMySQL/mysqlclient-python/issues/81 
and https://github.com/PyMySQL/mysqlclient-python/pull/106

Without it inserting `bytes` to a `VARBINARY()` or `BLOB` column can produce wrong warnings such as 

`Warning: Invalid utf8mb4 character string: 'B017'`

**Comment by terrycain** [comment]
Dont suppose you can provide a sample test case?

**Comment by LemonPi** [comment]
Sure I'll create it tomorrow afternoon

**Comment by LemonPi** [comment]
Hey @terrycain were you able to replicate the warnings with the code snippet?

**Comment by terrycain** [comment]
^^ :S
