### ISSUE TITLE
Deserialize json type data

### ISSUE THREAD

**Issue by scp10011** [aio-libs/aiomysql#334]
Query json type data return is str.
Automatically deserialize json type data based on description

    from mysql.connector import FieldType
    async def fetchall_deserialize(self):  
        obj = await self.fetchall()
        for name, ctype, *n in self.description:
            ctype = FieldType.get_info(ctype)
            if ctype == 'JSON':
                dname = name if isinstance(name, str) else name.decode()
                list(map(lambda x: x.update(dname=json.loads(x.pop(name, '{}'))), obj))
        return obj

**Comment by terrycain** [comment]
You could do this with a custom cursor class.

@jettify what do you think about adding somthing like this into `cursor.py` ?

**Comment by Nothing4You** [comment]
I believe this was already resolved in #343
