### ISSUE TITLE
New Release: 0.0.20?

### ISSUE THREAD

**Issue by evandroeisinger** [aio-libs/aiomysql#351]
Hey, there's a date for the launch of a new version? With the following MR: https://github.com/aio-libs/aiomysql/pull/339

Regards,

**Comment by jettify** [comment]
I will try to take a look, tonight.

**Comment by evandroeisinger** [comment]
@asvetlov @jettify @webknjaz any news?

**Comment by webknjaz** [comment]
@evandroeisinger I'm not doing releases for this project. I'm mostly into aiohttp+multidict + overall CI in this org.
@terrycain and @jettify do, rely on them.

**Comment by terrisgit** [comment]
PyMySql 0.9.3 is out, not sure if it's important.

**Comment by jettify** [comment]
New release is already on PyPI https://pypi.org/project/aiomysql/0.0.20/
