### ISSUE TITLE
aiomysql not support mysql 5.1

### ISSUE THREAD

**Issue by llzx373** [aio-libs/aiomysql#38]
In my test,aiomysql not support mysql 5.1, select statement not fetch result return.What can I do?

async def aio_test():
    con=await aiomysql.connect(host='instance_51',port=3306,user='user',password='passwd')
    cur=await con.cursor()
    await cur.execute('select 1')
    res=await cur.fetchone()
    print(res)
    await cur.close()
    con.close()

if **name** == '**main**':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(aio_test())

**Comment by jettify** [comment]
Does pymysql support mysql 5.1? If so should be easy to fix. I will take a
look when, get home

**Comment by jettify** [comment]
Looks like mysql 5.1 is not actively supported
http://dba.stackexchange.com/questions/10931/which-version-of-mysql-should-i-use
may be better option is to upgrade?

**Comment by llzx373** [comment]
In our product env,about 30%(1000+instances) is 5.1.x，upgrade is too hard。In another test，pymyql is work， now，I use gevent+pymysql work well。
But I think asyncio class（aiomysql etc.）is the best practice，fix this bug is very important for me。
thank you。

**Comment by jettify** [comment]
oh, I see, will try to find time on/after weekends.

**Comment by jettify** [comment]
mysql 5.1 is very old, there are little motivation to support it, but PR is welcome
