### ISSUE TITLE
Release 0.0.1

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiomysql#4]
Following features are not implemented or not finished:
1) documentation (#3)
2) ssl support 
3) more examples
4) ???
So my question, should I make initial release without docs and ssl support?

**Comment by asvetlov** [comment]
Fix SAConnection to accept dict, tuple, list and positional/keyword args like fresh aiopg.sa does.

**Comment by jettify** [comment]
Fixed. Alpha version released to pypi https://pypi.python.org/pypi/aiomysql
