### ISSUE TITLE
Integer interpolation into query is forced into a string, then fails.

### ISSUE THREAD

**Issue by francoposa** [aio-libs/aiomysql#423]
`"version": "==0.0.20"`

Query template to interpolate into. Have also tried %d and %s to try to get this to work
```
QUERY = """
SELECT
*
FROM
    whatever
WHERE
    whatever.id=%i
;"""
```

Relevant portion of my method:
```
async with self._engine.acquire() as conn:
    results: ResultProxy = await conn.execute(QUERY, 5)
```

Stack trace for error:
```
 File "/Users/franco/.virtualenvs/tg/lib/python3.6/site-packages/aiomysql/sa/connection.py", line 145, in _execute
    await cursor.execute(query, dp or None)
  File "/Users/franco/.virtualenvs/tg/lib/python3.6/site-packages/aiomysql/cursors.py", line 237, in execute
    query = query % self._escape_args(args, conn)
TypeError: %i format: a number is required, not str
```

**Comment by francojposa** [comment]
It's getting cast into a string way down in pymysql then aiomysql is complaining that it's a string

**Comment by Nothing4You** [comment]
I'm not sure why this would cause an issue with `%s`, as that's the way it should be used.
All values are turned into strings before being embedded in the executed query, so `%s` should work just fine.
If you still have an issue with this please open a new issue.

**Comment by michael-liumh** [comment]
I got same question

![Image](https://github.com/user-attachments/assets/50f3d895-d9bd-4919-bf1a-b3da3e8342e7)
