### ISSUE TITLE
'timeout' attribute not exist

### ISSUE THREAD

**Issue by khlyestovillarion** [aio-libs/aiomysql#43]
Hello, I have conversation regarding issue at aio-libs google group [here](https://groups.google.com/d/msg/aio-libs/HGv0lCMX-40/uQcnVaJdBgAJ) but there brief expanation again in any case:
`aiomysql.sa.create_engine()` method does not allow **timeout** parameter.
`aiomysql.sa.Engine` have no **timeout** attrubute.
`aiomysql.Pool` have no **timeout** attribute.
But all this situation were mentioned in docs.
I've provide pull request with docs updated(just remove this missleading 'timeouts') https://github.com/aio-libs/aiomysql/pull/42 if required.

I see that `aiomysql.connect()` method allow **connect_timeout** parameter and same we can provide to `aiomysql.sa.create_engine()` method without exception. But in any case we cannot get **timeout** attribute later from `sa.Engine` instance.

Also it seems that `sa.create_engine()` method and `aiomysql.Pool` class can receive all parameters that low level `aiomysql.connect()` method can. Maybe it reasonable to note some way regarding this in docs?

**Comment by jettify** [comment]
Thanks for report, would you like submit PR, with documentation update regarding information about passing connection arguments?

**Comment by khlyestovillarion** [comment]
@jettify Yes, of course - https://github.com/aio-libs/aiomysql/pull/44

**Comment by jettify** [comment]
Merged. Thank you!
