### ISSUE TITLE
Old style coroutines used the readthedocs 

### ISSUE THREAD

**Issue by Pradhvan** [aio-libs/aiomysql#436]
Hi! I was going through the documentation and found out that the [restructuredtext](https://github.com/aio-libs/aiomysql/blob/master/docs/index.rst) file still has the old-style coroutines instead of the async/await keyword, is there a particular reason for that?

If not I can submit a PR to change the code in the [readthedocs](https://aiomysql.readthedocs.io/en/latest/) to the new async/await feature.

**Comment by asvetlov** [comment]
Please do, excellent idea!
