### ISSUE TITLE
AttributeError: '_WindowsSelectorEventLoop' object has no attribute 'acquire'

### ISSUE THREAD

**Issue by hubinggg** [aio-libs/aiomysql#440]
async with pool.acquire() as conn:
        async with conn.cursor() as cur:
            # await cur.execute("SELECT 42;")
            insert_sql = "insert into article_test(title) values('{}') ".format(title)
            await cur.execute(insert_sql)

**Comment by asvetlov** [comment]
`loop` (`_WindowsSelectorEventLoop` instance) has not `acquire()` and never had it.
Perhaps you've muddled `pool` with `loop`.
