### ISSUE TITLE
asyncio.streams.IncompleteReadError is removed from python3.8

### ISSUE THREAD

**Issue by psafarov** [aio-libs/aiomysql#454]
https://github.com/aio-libs/aiomysql/blob/master/aiomysql/connection.py#L599 exception should be replaced

**Comment by TensorTom** [comment]
Upon running a stress test, I keep getting the error "AttributeError: module 'asyncio.streams' has no attribute 'IncompleteReadError'" and then my aiohttp server crashes.

**Comment by TensorTom** [comment]
Nevermind that. I see the branch referenced in the requirements file. She must be merged here,

**Comment by tonal** [comment]
Manky path:
```python
def aiomysql_path():
  try:
    from aiomysql.connection import IncompleteReadError
    return
  except:
    pass

  try:
    from asyncio.streams import IncompleteReadError
    return
  except:
    pass

  import asyncio
  from pymysql import OperationalError

  async def _read_bytes(self, num_bytes):
    try:
      data = await self._reader.readexactly(num_bytes)
    except asyncio.exceptions.IncompleteReadError as e:
      msg = "Lost connection to MySQL server during query"
      raise OperationalError(2013, msg) from e
    except (IOError, OSError) as e:
      msg = "Lost connection to MySQL server during query (%s)" % (e,)
      raise OperationalError(2013, msg) from e
    return data

  from aiomysql.connection import Connection
  Connection._read_bytes = _read_bytes
```

**Comment by spumer** [comment]
Can you up lib version? Cause current version is too old and no fix at last release (0.0.20)

**Comment by spumer** [comment]
@webknjaz can you help?

**Comment by webknjaz** [comment]
Ask @terrycain and @jettify @ #466

**Comment by spumer** [comment]
@ndavydovdev release published 14 days ago: https://github.com/aio-libs/aiomysql/issues/466#issuecomment-734445707

**Comment by ndavydovdev** [comment]
> @ndavydovdev release published 14 days ago: https://github.com/aio-libs/aiomysql/issues/466#issuecomment-734445707

Hmmm, I think, databases uses older version, thanks
