### ISSUE TITLE
'trans.rollback()' is not working correct

### ISSUE THREAD

**Issue by khlyestovillarion** [aio-libs/aiomysql#46]
I've tried to use standart code from docs:
```python
with (yield from engine) as conn:
    trans = yield from conn.begin()
    try:
        yield from conn.execute("insert into x (a, b) values (1, 2)")
    except Exception:
        yield from trans.rollback()
    else:
        yield from trans.commit()
```
but in case if `trans.rollback()` was called for some reason then during closing the connection we will receive an exception:
```
  File "/home/legat/Projects/ecoisme/env/lib/python3.5/site-packages/aiomysql/sa/engine.py", line 191, in __exit__
    self._engine.release(self._conn)
  File "/home/legat/Projects/ecoisme/env/lib/python3.5/site-packages/aiomysql/sa/engine.py", line 116, in release
    raise InvalidRequestError("Cannot release a connection with "
aiomysql.sa.exc.InvalidRequestError: Cannot release a connection with not finished transaction
```

I think that `_rollback_impl()` method form SAConnection instance should be updated the same as it was at aiopg library [at this commit](https://github.com/aio-libs/aiopg/commit/1c208f4efbce81890334652f0bb949382340a02f)

A little bit later I will make the same/test and provide pull request.

**Comment by jettify** [comment]
Thanks! Fixed via https://github.com/aio-libs/aiomysql/commit/44ff6017f6c8f01e8d246659a6fc019e68eaf32d

**Comment by khlyestovillarion** [comment]
@jettify Thanks for you!
