### ISSUE TITLE
LAST_INSERT_ID() returns 0 when sharing a cursor.execute(...) call with INSERT

### ISSUE THREAD

**Issue by Pytato** [aio-libs/aiomysql#477]
Windows 10 Home 1903 (18362.720)
Python 3.8.2 x64, aiomysql 0.0.20
MariaDB 10.4

Using `Pool` with `auto_commit=True`

Querying `SELECT LAST_INSERT_ID();` within the same `await cursor.execute(...)` call as the `INSERT...;` query the `LAST_INSERT_ID()` should be referencing causes the next `await cursor.fetchone()` call to yield an empty list (this is on a "clean" cursor).

A current workaround involves splitting the `SELECT LAST_INSERT_ID();` and `INSERT...;` queries into separate `await cursor.execute(...)` calls. This yields expected behaviour of `await cursor.fetchone()`. 

I have not tested whether this behaviour is inherited from PyMySQL, rather than aiomysql.

Considering most documentation on SQL best practice indicates it is ideal to keep the `SELECT LAST_INSERT_ID();` close to whatever `AUTO_INCREMENT` it is referencing, requiring two `await cursor.execute(...)` calls may be considered a non-ideal case. Please do let me know if I have configured my environment in a fashion that causes this behaviour.

Many thanks
fwf

**Comment by desprit** [comment]
@Pytato 

Have you tried cursor.lastrowid?

**Comment by Pytato** [comment]
I have not, that would seem ideal as a means of avoiding more queries than required.

I'll consider that a solution to the issue, as it effectively closes any complaint I had about making more than one query.

Thanks
