### ISSUE TITLE
Can't connect to MySQL server on ' '

### ISSUE THREAD

**Issue by Sultan91** [aio-libs/aiomysql#487]
Trying to create docker-compose file with asyncio and mysql services:
_______________________________________________
version: '3'
services:
    web:
      build: .
      command: python /code/app.py
      ports:
       - "8084:80"
      volumes:
       - .:/code
      links:
       - mysql
      depends_on:
        - mysql
      hostname: myappserver
    mysql:
        hostname: mysql_server
        image: mysql
        environment:
            - MYSQL_USER=aiomysql
            - MYSQL_PASSWORD=mypass
            - MYSQL_DATABASE=test_db
            - MYSQL_ROOT_PASSWORD=mypass
        ports:
            - 3307:3307
        volumes:
            - /tmp/aiomysql:/var/run/mysqld/
____________________________________________________________
According to aiomysql tutorial I have to supply mysql IP address:
`async def test_example():
    conn = await aiomysql.connect(host='mysql', port=3307,
                                       user='aiomysql', password='mypass', db='test_db',
                                       loop=loop)
    cur = await conn.cursor()
    await cur.execute("SELECT Host,User FROM user")
`
What should I put in place of `host`?
Things i tried to put:
         `mysql_server`
          `mysql`

**Comment by Sultan91** [comment]
It appeared that, mysql service didn't have enough time finish setup. After I've put time.sleep(10)  i was able to read DB. However, after I have tried to use 
` conn = await aiomysql.connect(host='mysql', port=3306,
                                       user='root', password='mypass', db='mysql',
                                       connect_timeout=60,
                                       loop=loop)`
With `connect_timeout` param it wasn't waiting and was failing with the same exception(

**Comment by terrycain** [comment]
Yeah connect_timeout doesn't do exactly what it should :/

**Comment by Sultan91** [comment]
That's interesting, maybe it is a bug or I just misunderstood this parameter

**Comment by terrycain** [comment]
Its an oversight, connect/read/write timeouts need to be overhauled. Feel free to PR it :D

**Comment by jda5** [comment]
@Sultan91 I am having this issue also! What exactly did you do to fix it? Where did you place the `sleep(10)` command?
