### ISSUE TITLE
Support current PyMySQL version

### ISSUE THREAD

**Issue by ymj4023** [aio-libs/aiomysql#518]
can the aiomysql pymysql>=0.9.3?

**Comment by suiyuex** [comment]
in this [file](https://github.com/aio-libs/aiomysql/blob/master/requirements-dev.txt), should support

**Comment by 515k4** [comment]
Question is about >=0.9.3 while the file states PyMySQL>=0.9,<=0.9.3

In any case, can somebody update release on pypi with those reqs? Pypi still insists on <=0.9.2.

**Comment by fabaff** [comment]
PyMySQL is already 0.10.1.

The complete release pinning should be removed and the relevant functions covered by unit tests as there is no proper release cycle for aiomysql, see also https://github.com/aio-libs/aiomysql/issues/466

**Comment by fabaff** [comment]
This issue was not addressed by 0.0.21.

**Comment by long2ice** [comment]
recommended [asyncmy](https://github.com/long2ice/asyncmy)

**Comment by suiyuex** [comment]
@long2ice nice
