### ISSUE TITLE
special characters in password causes connecting failed

### ISSUE THREAD

**Issue by ChristianYeah** [aio-libs/aiomysql#522]
the password like ```a/b``` is not able to connect to the mysql server, even if I percent-encoded the password to ```a%2Fb```

**Comment by suiyuex** [comment]
@ChristianYeah  password contains special characters works for me , any further detail maybe needed
![image](https://user-images.githubusercontent.com/51814639/92301521-1fc00700-ef97-11ea-82af-aed32ba6ebe8.png)

**Comment by ChristianYeah** [comment]
> @ChristianYeah password contains special characters works for me , any further detail maybe needed
> ![image](https://user-images.githubusercontent.com/51814639/92301521-1fc00700-ef97-11ea-82af-aed32ba6ebe8.png)

 I believe it's not the problem of aiomysql itself. actually, I'm using the package databases aiomysql driver as the driver to manage connections, and the fundamental is caused by databases, or more specifically, it's the problem of the correctness of integration for both.
as far as I can determine,

1. databases package only accepts connection uri, it causes trouble when kargs are passed, and of course the uri must be percent-encoded

2. databases won't decode the percent-encoded uri to aiomysql, and aiomysql seems not responding to the encoded uri correctly, or it won't decode the uri.

I will find an alternative way to solve this any way. Thank you @suiyuex .
