### ISSUE TITLE
AioMysql breaking under latest pymysql release

### ISSUE THREAD

**Issue by syleishere** [aio-libs/aiomysql#556]
**Compiling it under buildozer with kivy, following logs from android phone:**

01-11 20:14:22.728 16052 16090 I python : Android kivy bootstrap done. name is main
01-11 20:14:22.728 16052 16090 I python : AND: Ran string
01-11 20:14:22.728 16052 16090 I python : Run user program, change dir and execute entrypoint
01-11 20:14:22.844 16052 16090 I python : Traceback (most recent call last):
01-11 20:14:22.844 16052 16090 I python : File "/home/dan/python/apps/sunsaturn/helloworld/.buildozer/android/app/main.py", line 5, in
01-11 20:14:22.844 16052 16090 I python : File "/home/dan/python/apps/sunsaturn/helloworld/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/hellow
orld/aiomysql/init.py", line 32, in
01-11 20:14:22.844 16052 16090 I python : File "/home/dan/python/apps/sunsaturn/helloworld/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/hellow
orld/aiomysql/connection.py", line 19, in
01-11 20:14:22.844 16052 16090 I python : ModuleNotFoundError: No module named 'pymysql.util'
01-11 20:14:22.844 16052 16090 I python : Python for android ended.

**Comment by Nothing4You** [comment]
closing in favor of #518
