### ISSUE TITLE
Add an `rsa` extra require?

### ISSUE THREAD

**Issue by JulienPalard** [aio-libs/aiomysql#557]
What about adding an `aiomysql[rsa]` extra require, depending on `PyMySQL[rsa]`, to pull cryptography?

It would have an advantage over manually installing cryptography: to pull the right version. Currently PyMySQL does not requires any specific version of cryptography, but could in the future.

**Comment by Nothing4You** [comment]
if that's added `ed25519` should probably also be added

**Comment by Nothing4You** [comment]
`ed25519` should be added when support for `ed25519` is implemented, RSA will be available in the next release.
