### ISSUE TITLE
is aiomysql still active? 

### ISSUE THREAD

**Issue by ygl-rg** [aio-libs/aiomysql#580]
Hi All

    I noticed the last commit was date back to Nov 2020. I am curious whether this library is still active.

Regards

ygl

**Comment by fabaff** [comment]
I recommend not to use it for new projects as for a lot of distributions (Fedora, NixOS, CentOS and probably more) `aiomysql` is broken. There is no support for later `pymysql` (e.g., #518) releases which is big show-stopper.

**Comment by ygl-rg** [comment]
Hi fabaff

    you means I should use pymysql directly?

**Comment by ygl-rg** [comment]
I have switched to tornado...

thx

**Comment by long2ice** [comment]
recommended [asyncmy](https://github.com/long2ice/asyncmy)
