### ISSUE TITLE
Unable to import aiomysql while running as uid without account

### ISSUE THREAD

**Issue by Nothing4You** [aio-libs/aiomysql#587]
Hi,

I'm trying to run a script inside a container.
I don't know the UID the container runs as at build time and I don't want to initialize the container as root, so I can't workaround by creating the user at runtime.
This means that at runtime the UID the script is running as does not have an entry in `/etc/passwd`.

This is however expected at least in the current master at the time of writing, not sure if there are other places where this is expected in the code:
https://github.com/aio-libs/aiomysql/blob/0a8af2355562ea961477738d66b3334332447186/aiomysql/connection.py#L45

Currently when trying to `import aiomysql` the following exception is raised:
```
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import aiomysql
  File "/usr/local/lib/python3.7/site-packages/aiomysql/__init__.py", line 32, in <module>
    from .connection import Connection, connect
  File "/usr/local/lib/python3.7/site-packages/aiomysql/connection.py", line 45, in <module>
    DEFAULT_USER = getpass.getuser()
  File "/usr/local/lib/python3.7/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 12345'
```

### To reproduce:
`Dockerfile`
```Dockerfile
FROM python:3.7-slim-buster

RUN pip3 install aiomysql

COPY demo.py /app/

WORKDIR /app

ENTRYPOINT ["/usr/bin/env", "python3", "demo.py"]
```

`demo.py`
```py
print("Hello World from container")
import aiomysql
```

1. build container `DOCKER_BUILDKIT=1 docker build -t test-py .`
2. run container as uid 12345 `docker run --rm -it --user 12345 test-py`
3. see KeyError

**Comment by Nothing4You** [comment]
@chrisburr do you want to create a PR from your commit?

**Comment by chrisburr** [comment]
I'm surprised I hadn't already 😅.

Done in https://github.com/aio-libs/aiomysql/pull/687

**Comment by Miguelme** [comment]
Hello, I'm running into the same issue for a deployment. How can we include this fix in our code? The latest release I see on pypi is from november
