### ISSUE TITLE
Any plans to support PyMySQL-1.0.2 

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [aio-libs/aiomysql#592]
Current version aiomysql require PyMySQL<=0.9.3,>=0.9
Do exist any planning when will be supported PyMySQL > 1.0.0
for example for TLS support.

**Comment by synodriver** [comment]
This project haven't updated for around half year. Maybe something happened.

**Comment by fabaff** [comment]
See #518

**Comment by Nothing4You** [comment]
closing in favor of #518
