### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by synackSA** [aio-libs/aiomysql#609]
We haven't seen any activity from any of the devs on this project for quite sometime. Has this been abandoned?

**Comment by aryaniyaps** [comment]
small bump on this guys @jettify is there any chance maintenance could be resumed? SQLAlchemy dropped support for this driver because it was unmaintained for a while :/

**Comment by asvetlov** [comment]
I have no capacity for contribution to aiomysql myself, sorry.

If somebody wants to be a champion -- please write a comment.

**Comment by Nothing4You** [comment]
no longer unmaintained
