### ISSUE TITLE
Enable by default utf8 encoding

### ISSUE THREAD

**Issue by GMLudo** [aio-libs/aiomysql#62]
Hi,

If I import this SQL file in MySQL DB with this line: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/config/create.sql#L110

When I retrieve this line with aiomysql, I have **??????????????** string instead of **フレームワークのベンチマーク**.

Except if I add two parameters in the aiomysql connection: 

                charset='utf8',
                use_unicode=True,

At least to me, it should be the default behaviour of aiomysql.

What do you think ?

Have a nice day.

**Comment by jettify** [comment]
I tend to agree with you about  'utf-8' but `pymysql` uses other default value and I want defaults of `aiomysql` and `pymysql` to be the same.

**Comment by GMLudo** [comment]
And if I understand correctly, pymysql tries to have the same behaviour as mysqldb.

Thanks for your answer.

**Comment by methane** [comment]
And latin1 is the MySQL's default.
http://dev.mysql.com/doc/refman/5.6/en/mysql-command-options.html#option_mysql_default-character-set

**Comment by methane** [comment]
@jettify FYI, I recommend you to use 'utf8mb4' instead of 'utf8'.
MySQL's utf8 doesn't cover unicode.
