### ISSUE TITLE
Echo option for default cursor

### ISSUE THREAD

**Issue by Drizzt1991** [aio-libs/aiomysql#63]
This line:
https://github.com/aio-libs/aiomysql/blob/master/aiomysql/connection.py#L365

``` python
        cur = cursor(self, self._echo) if cursor else self.cursorclass(self)
```

We should pass echo param to cursorclass too, don't we?

**Comment by jettify** [comment]
closed via https://github.com/aio-libs/aiomysql/pull/77

**Comment by Drizzt1991** [comment]
GJ @Reonaydo =)
