### ISSUE TITLE
Issue with unbuffered cursor

### ISSUE THREAD

**Issue by hiepnq94** [aio-libs/aiomysql#635]
If the previous query isn't iterated to the end, the subsequent query raises `pymysql.err.InternalError: Packet sequence number wrong` with a warning `RuntimeWarning: coroutine 'MySQLResult._finish_unbuffered_query' was never awaited`.

Reproduction:
```py
# with cursorclass=SSCursor set in connection
async with conn.cursor() as cur:
    await cur.execute("""SELECT 1""")
    await cur.execute("""SELECT 2""")
    # raise
```

It seems the problem is in this line, as it should be `await`-ed:
https://github.com/aio-libs/aiomysql/blob/45d241e48072d230cef8403e8178302ab31d1aef/aiomysql/connection.py#L650

(python 3.10.0, aiomysql 0.0.22)

**Comment by Nothing4You** [comment]
thanks for the report!

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Same patch produced the same failure twice.

Relevant files:
- aiomysql/connection.py: seeded from gold changed files (offline eval)
- tests/test_sscursor.py: seeded from gold changed files (offline eval)

Attempts:
Attempt 1: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Attempt 2: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Token usage: 11257/80000
