### ISSUE TITLE
When the host parameter is the domain name, a thread will appear every time a connection is created, but it will not appear when it is ip.

### ISSUE THREAD

**Issue by conlin-huang** [aio-libs/aiomysql#641]
##### test_mysql.py

```python
import asyncio
import aiomysql

import sys

host = sys.argv[1]


async def test_example(loop):
    pool = await aiomysql.create_pool(loop=loop, **{
            'db': 'mysql',
            'user': 'root',
            'password': '123456',
            'host': host,
            'port': 3306,
            'minsize': 20,
            'maxsize': 50
        })
    async with pool.acquire() as conn:
        async with conn.cursor() as cur:
            await cur.execute("SELECT 42;")
            print(cur.description)
            (r,) = await cur.fetchone()
            assert r == 42
    pool.close()
    await pool.wait_closed()

    await asyncio.sleep(50000)

loop = asyncio.get_event_loop()
loop.run_until_complete(test_example(loop))

```

`python test_mysql.py 'mysql.test.com'`
`python test_mysql.py '192.168.234.128'`

##### htop
![htop](https://user-images.githubusercontent.com/36884738/147464560-98b9fcdc-56b1-4052-98f2-c4e34befba0f.png)

##### reason
![1](https://user-images.githubusercontent.com/36884738/147464667-1fb4df2d-6c38-486b-b68d-e8e29a9a629c.png)

![2](https://user-images.githubusercontent.com/36884738/147464675-6b0d973c-ad5b-4afb-827a-6773efd4e405.png)

**Comment by Nothing4You** [comment]
Hi @conlin-huang,

I do not believe that this is an issue with aiomysql.
We do not handle DNS resolution ourselves, it's passed on to the underlying Python asyncio implementation.

You can reproduce the same behavior with the following example:
```py3
import asyncio
import socket


async def test_example(loop):
    tasks = []

    for i in range(5):
        tasks.append(loop.getaddrinfo(f"{i}.test.com", 80, proto=socket.IPPROTO_TCP))

    await asyncio.gather(*tasks)
    print("dns resolved")

    await asyncio.sleep(300)


loop = asyncio.new_event_loop()
loop.run_until_complete(test_example(loop))
```

**Comment by conlin-huang** [comment]
I agree with you, I just hope that the developers who using 'aiomysql' pay attention to this issue and handling DNS themselves.

> Hi @conlin-huang,
> 
> I do not believe that this is an issue with aiomysql. We do not handle DNS resolution ourselves, it's passed on to the underlying Python asyncio implementation.
> 
> You can reproduce the same behavior with the following example:
> 
> ```python
> import asyncio
> import socket
> 
> 
> async def test_example(loop):
>     tasks = []
> 
>     for i in range(5):
>         tasks.append(loop.getaddrinfo(f"{i}.test.com", 80, proto=socket.IPPROTO_TCP))
> 
>     await asyncio.gather(*tasks)
>     print("dns resolved")
> 
>     await asyncio.sleep(300)
> 
> 
> loop = asyncio.new_event_loop()
> loop.run_until_complete(test_example(loop))
> ```

I agree with you, I just hope that the developers who using 'aiomysql' pay attention to this issue and handling DNS themselves.
