### ISSUE TITLE
The project is looking for new maintainer

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiomysql#647]
Current maintainers are not active now.
I have no spare time for this project, sorry.

If somebody wants to help -- please write here.

**Comment by Nothing4You** [comment]
I would be interested in helping with this.

**Comment by asvetlov** [comment]
Great!

**Comment by asvetlov** [comment]
@Nothing4You invite with writ access is sent.
I suggest starting with iterating over existing pull requests first, then triaging created issues.
Please feel free to contact me if you need any help.
Also, please contact me if you are in doubt.
