### ISSUE TITLE
Add RTD maintainer

### ISSUE THREAD

**Issue by Nothing4You** [aio-libs/aiomysql#719]
To be able to manage RTD configuration, such as enabling [PR builds](https://docs.readthedocs.io/en/stable/pull-requests.html), please add @webknjaz and/or me as maintainer on RTD.

**Comment by asvetlov** [comment]
Sorry for the delay. What is your RTD login name?

**Comment by asvetlov** [comment]
@webknjaz was added

**Comment by Nothing4You** [comment]
thanks, I'm also Nothing4You there.

**Comment by webknjaz** [comment]
I've added you and enabled the PR builds.
