### ISSUE TITLE
Improper error shown - (2003, "Can't connect to MySQL server on 'localhost'")

### ISSUE THREAD

**Issue by leothewolf** [aio-libs/aiomysql#792]
### Describe the bug

Well I formatted my pc and had to reinstall all the stuff and while I started working with my code I started receiving error ``(2003, "Can't connect to MySQL server on 'localhost'")`` I was not expecting that as my code worked flawless and at that time my discord bot which uses the same code was up and running well. So after two hours of going through all code I found that I had added ``db`` parameter in ``aiomysql.create_pool`` and I had forgot to create a database with the db mentioned there so that was the problem! So what I want is it should throw error that ``db is not found`` rather than ``(2003, "Can't connect to MySQL server on 'localhost'")``

### To Reproduce

I am running latest version of python 3.10 and pip installed aiomysql

Just dont make a database and try creating ``aiomysql.create_pool`` object with mentioning db you will get the error!

I used following code:
```
import asyncio
import aiomysql

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)


async def test_example():
    try:
        conn = await aiomysql.create_pool(host='localhost', port=3306, user='user', password='pass',loop=loop,db="uncreated_db")
    except Exception as e:
        print(e)

loop.run_until_complete(test_example())
```

### Expected behavior

Will throw this error : ``(2003, "Can't connect to MySQL server on 'localhost'")``

### Logs/tracebacks

```python-traceback
Will throw this error : ``(2003, "Can't connect to MySQL server on 'localhost'")``
```

### Python Version

```console
$ Python 3.10.4
```

### aiomysql Version

```console
$ python -m pip show aiomysql
```

### PyMySQL Version

```console
1.0.2
```

### SQLAlchemy Version

```console
1.0.2
```

### OS

Windows

### Database type and version

```console
MySQL : 8.0.29
```

### Code of Conduct

- [x] I agree to follow the aio-libs Code of Conduct

**Comment by Nothing4You** [comment]
Hm, the error for unknown database is raised, but due to this happening while attempting to connect it's reraised as connection error:

```pytb
Traceback (most recent call last):
  File ".../aiomysql/aiomysql/connection.py", line 540, in _connect
    await self._request_authentication()
  File ".../aiomysql/aiomysql/connection.py", line 833, in _request_authentication
    auth_packet = await self._read_packet()
  File ".../aiomysql/aiomysql/connection.py", line 641, in _read_packet
    packet.raise_for_error()
  File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'uncreated_db'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../aiomysql/issue-792.py", line 13, in <module>
    asyncio.run(test_example())
  File ".../.asdf/installs/python/3.10.2/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File ".../.asdf/installs/python/3.10.2/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File ".../aiomysql/issue-792.py", line 7, in test_example
    conn = await aiomysql.create_pool(host='localhost', port=3306, user='root', password='', db="uncreated_db")
  File ".../aiomysql/aiomysql/pool.py", line 29, in _create_pool
    await pool._fill_free_pool(False)
  File ".../aiomysql/aiomysql/pool.py", line 182, in _fill_free_pool
    conn = await connect(echo=self._echo, loop=self._loop,
  File ".../aiomysql/aiomysql/connection.py", line 75, in _connect
    await conn._connect()
  File ".../aiomysql/aiomysql/connection.py", line 558, in _connect
    raise OperationalError(2003,
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost'")
```

The same applies when just connecting without a pool.

in comparison, PyMySQL raises the database error:
```pytb
Traceback (most recent call last):
  File ".../aiomysql/issue-792-pm.py", line 4, in <module>
    connection = pymysql.connect(
  File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'uncreated_db'")
```

**Comment by Nothing4You** [comment]
PyMySQL has a little more logic there to only create `OperationalError` for `OSError` and `IOError`: https://github.com/PyMySQL/PyMySQL/blob/v1.0.2/pymysql/connections.py#L655-L664

Looks like PyMySQL has been doing this since about 2015: https://github.com/PyMySQL/PyMySQL/commit/125daaa48e40f441936577d96fb1b5615cd8d17e

**Comment by leothewolf** [comment]
> Hm, the error for unknown database is raised, but due to this happening while attempting to connect it's reraised as connection error:
> 
> ```
> Traceback (most recent call last):
>   File ".../aiomysql/aiomysql/connection.py", line 540, in _connect
>     await self._request_authentication()
>   File ".../aiomysql/aiomysql/connection.py", line 833, in _request_authentication
>     auth_packet = await self._read_packet()
>   File ".../aiomysql/aiomysql/connection.py", line 641, in _read_packet
>     packet.raise_for_error()
>   File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
>     err.raise_mysql_exception(self._data)
>   File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
>     raise errorclass(errno, errval)
> pymysql.err.OperationalError: (1049, "Unknown database 'uncreated_db'")
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File ".../aiomysql/issue-792.py", line 13, in <module>
>     asyncio.run(test_example())
>   File ".../.asdf/installs/python/3.10.2/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File ".../.asdf/installs/python/3.10.2/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
>     return future.result()
>   File ".../aiomysql/issue-792.py", line 7, in test_example
>     conn = await aiomysql.create_pool(host='localhost', port=3306, user='root', password='', db="uncreated_db")
>   File ".../aiomysql/aiomysql/pool.py", line 29, in _create_pool
>     await pool._fill_free_pool(False)
>   File ".../aiomysql/aiomysql/pool.py", line 182, in _fill_free_pool
>     conn = await connect(echo=self._echo, loop=self._loop,
>   File ".../aiomysql/aiomysql/connection.py", line 75, in _connect
>     await conn._connect()
>   File ".../aiomysql/aiomysql/connection.py", line 558, in _connect
>     raise OperationalError(2003,
> pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost'")
> ```
> 
> The same applies when just connecting without a pool.
> 
> in comparison, PyMySQL raises the database error:
> 
> ```
> Traceback (most recent call last):
>   File ".../aiomysql/issue-792-pm.py", line 4, in <module>
>     connection = pymysql.connect(
>   File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
>     self.connect()
>   File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
>     self._request_authentication()
>   File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
>     auth_packet = self._read_packet()
>   File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
>     packet.raise_for_error()
>   File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
>     err.raise_mysql_exception(self._data)
>   File ".../aiomysql/venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
>     raise errorclass(errno, errval)
> pymysql.err.OperationalError: (1049, "Unknown database 'uncreated_db'")
> ```

Ohh ok ok I didnt notice the database error but it would be great if it somehows appears later on like we atleast know

**Comment by leothewolf** [comment]
> PyMySQL has a little more logic there to only create `OperationalError` for `OSError` and `IOError`: https://github.com/PyMySQL/PyMySQL/blob/v1.0.2/pymysql/connections.py#L655-L664
> 
> Looks like PyMySQL has been doing this since about 2015: [PyMySQL/PyMySQL@125daaa](https://github.com/PyMySQL/PyMySQL/commit/125daaa48e40f441936577d96fb1b5615cd8d17e)

Well it would be great if we can somehow make the database not found error later on so that the user knows that its because of database as there might be people like me who wont notice the error within error

**Comment by AndreMPCosta** [comment]
Why do we have this bit of code:

```python
  except Exception as e:
      if self._writer:
          self._writer.transport.close()
      self._reader = None
      self._writer = None
      raise OperationalError(2003,
                             "Can't connect to MySQL server on %r" %
                             self._host) from e
```

Instead of raising the original exception? We lose all the info and the error code (auth failed for 1045 for example, 1049 database not found, etc). 

This approach does not make much sense, putting everything as an Operational Error 2003 code.

**Comment by Nothing4You** [comment]
#839 should resolve this.

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Context collection made no progress (located the same files again).

Relevant files:
- aiomysql/connection.py: path components match issue terms; bm25 rerank score=86.761; matched issue terms: error, can, t, connect, mysql, server; bm25 rerank score=80.989; matched issue terms: error, can, t, connect, mysql, server; bm25 rerank score=81.066; matched issue terms: error, can, t, connect, mysql, server; bm25 rerank score=81.066; matched issue terms: error, can, t, connect, mysql, server
- aiomysql/cursors.py: path components match issue terms; bm25 rerank score=52.714; matched issue terms: error, can, t, mysql, server, i; bm25 rerank score=58.386; matched issue terms: error, can, t, mysql, server, i; bm25 rerank score=60.396; matched issue terms: error, can, t, mysql, server, i; bm25 rerank score=60.396; matched issue terms: error, can, t, mysql, server, i
- tests/test_issues.py: test file; bm25 rerank score=58.338; matched issue terms: error, 2003, can, t, connect, mysql; bm25 rerank score=59.510; matched issue terms: error, 2003, can, t, connect, mysql; bm25 rerank score=59.510; matched issue terms: error, 2003, can, t, connect, mysql
- tests/conftest.py: test file; bm25 rerank score=49.235; matched issue terms: t, connect, mysql, server, localhost, i; bm25 rerank score=49.895; matched issue terms: t, connect, mysql, server, localhost, i; bm25 rerank score=49.895; matched issue terms: t, connect, mysql, server, localhost, i
- tests/test_sha_connection.py: test file; bm25 rerank score=41.825; matched issue terms: mysql, server, stuff, not, at, time; bm25 rerank score=43.290; matched issue terms: mysql, server, stuff, not, at, time; bm25 rerank score=43.290; matched issue terms: mysql, server, stuff, not, at, time
- aiomysql/pool.py: requested by planner next_checks; bm25 rerank score=37.866; matched issue terms: error, t, connect, mysql, all, while; bm25 rerank score=37.866; matched issue terms: error, t, connect, mysql, all, while

Attempts:
No patch attempts were made.

Token usage: 30700/100000

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Same patch produced the same failure twice.

Relevant files:
- aiomysql/connection.py: seeded from gold changed files (offline eval)
- tests/test_connection.py: seeded from gold changed files (offline eval)
- tests/test_issues.py: seeded from gold changed files (offline eval)

Attempts:
Attempt 1: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Attempt 2: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Token usage: 16212/80000
