### ISSUE TITLE
Inconsistant results after insert using sa

### ISSUE THREAD

**Issue by nealie** [aio-libs/aiomysql#86]
Using aiomysql.sa with MySQL 5.5.49 I find that when I insert columns into a database then subsequently query the it, the result I get can sometimes include the inserted value and sometimes not.

If I essentially disable the connection pool by setting the minsize and maxsize to 1 then all works as expected. This is however not any use for production.

Attached is a simple test program and schema which should handily reproduce the problem:
[test.py.txt](https://github.com/aio-libs/aiomysql/files/328073/test.py.txt)
[test.sql.txt](https://github.com/aio-libs/aiomysql/files/328074/test.sql.txt)

**Comment by jettify** [comment]
Could you try to pass `autocommit=True` and test the issue? Looks like autocommit is not enabled.

**Comment by nealie** [comment]
autocommit=True seems to fix the problem at least for the example.
Does this mean that I don't need the transaction code? It's a bit worrying that a transaction doesn't work properly as this means that there's no way to make multiple inserts atomic.

**Comment by jettify** [comment]
If you need multiple atomic inserts execute `yield from sa_conn.execute('commit');`  manualy or use use dedicated context manager see: https://github.com/aio-libs/aiomysql/blob/master/tests/pep492/test_async_with.py#L212-L215

for more info you can find in this issue: https://github.com/aio-libs/aiomysql/issues/70

I somehow to forget to add more helpers for such case, hope to do something about this soon

**Comment by jettify** [comment]
closing this one in favor https://github.com/aio-libs/aiomysql/issues/70
