### ISSUE TITLE
Add ssl support

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiomysql#9]
1) add _ssl_ support by passing `ssl.SSLContext` to `asyncio.open_connection`.
2) start additional _mysql_ instance at travis ci and try to pass test suite.

**Comment by terrycain** [comment]
Just for reference sake, can't pass SSLContext to open_connection as MySQL likes to switch to TLS mid conversation :unamused: Though I do have a working (mostly I think) version that does the TLS'ing but it needs some testing.

**Comment by 4tochka** [comment]
https://github.com/aio-libs/aiomysql/pull/156   You can check this brach

**Comment by terrycain** [comment]
Ahh yeah I saw that literally after I did it :disappointed:

**Comment by jettify** [comment]
Feature available and released.
