### ISSUE TITLE
How to get the log for sql

### ISSUE THREAD

**Issue by 631068264** [aio-libs/aiomysql#92]
How to get the log for sql statement

**Comment by jettify** [comment]
Hi, sorry for late reply what is you use case?

**Comment by sseg** [comment]
Perhaps in the same vein: I'm trying to log escaped and formatted SQL statements. I believe this should be accomplished using the `echo` option, but that doesn't seem to be used by the cursor.

**Comment by jettify** [comment]
I will review echo option and fix logging, in mean time you can use `cursor.mogrify ` to construct escaped and formatted SQL https://github.com/aio-libs/aiomysql/blob/master/tests/test_cursor.py#L278-L288

**Comment by sseg** [comment]
Cool, thanks. Similarly setting `cursor._echo` works in local uses.

**Comment by jettify** [comment]
Old issue closing for now, feel free to crate new one
