### ISSUE TITLE
Wrong ArgumentError message

### ISSUE THREAD

**Issue by Dodge-KSV** [aio-libs/aiomysql#96]
There is a copy-paste error message mistake into aiomysql/sa/connection.py:
    
    dp = _distill_params(multiparams, params)
    if len(dp) > 1:
        raise exc.ArgumentError("aiopg doesn't support executemany")    # aiopg => aiomysql

**Comment by asvetlov** [comment]
Fixed by d9fe87a  
Thanks for report!
